steps:
  - name: 'gcr.io/cloud-builders/gcloud-slim'
    args:
    - functions
    - deploy
    - ${_NAME}
    - --region=${_REGION}
    - --source=.
    - --entry-point=entry
    - --runtime=nodejs10
    - --trigger-http
    - --memory=128MB
